[default]
src = 'src'
out = 'out'
libs = ['lib']
solc-version = "0.8.9"
verbosity = 2
optimizer = true
optimizer_runs = 1000000
gas_reports = ["RoyaltyRegistry", "MockRoyaltyRegistry"]

# See more config options https://github.com/gakonst/foundry/tree/master/config
